name: Chess
on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  chess:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.issue.number == 1 && startsWith(github.event.comment.body, 'chess move '))
    steps:
      - uses: actions/checkout@v3
      - uses: nicklegan/github-readme-chess-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
